[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
dotenv = "0.15.0"
env_logger = "0.11.6"
lazy_static = "1.5.0"


