//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "token_type_enum")]
pub enum TokenTypeEnum {
    #[sea_orm(string_value = "access_token")]
    AccessToken,
    #[sea_orm(string_value = "authorized_token")]
    AuthorizedToken,
    #[sea_orm(string_value = "app_token")]
    AppToken,
}
