//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::address::Entity as Address;
pub use super::country::Entity as Country;
pub use super::post::Entity as Post;
pub use super::property::Entity as Property;
pub use super::token::Entity as Token;
pub use super::user::Entity as User;
